---
apiVersion: v1
kind: ImageStream
metadata:
  name: freeboard
---
apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: freeboard
  name: freeboard
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: freeboard:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/itsbcit/openshift-freeboard.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers: []
status:
  lastVersion: 0
